runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:Mvr+7il5yl5Aqb8XtmDC2oCooVeQExxLytMZ3SRM8E8=
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: cst323activity
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_SOCKET: "/cloudsql/shod-268016:us-central1:shod"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "shod-268016:us-central1:shod"
